spring.application.name=order_service
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:shopdb}
spring.datasource.username: ${DB_USERNAME:postgres}
spring.datasource.password: ${DB_PASSWORD:secret}
spring.datasource.driver-class-name: org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate          
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA:public}

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=${DB_SCHEMA:public}
spring.liquibase.liquibase-schema=${DB_SCHEMA:public}

server.port=8082

logging.leve.liquibase=INFO
logging.level.org.hibernate.SQL=${LOG_SQL:WARN}